Repository FRONT-END-BOOTCAMP-PLUS-5/BoGam, pull requests merged in 2025-08, with the labels that each got.

#11 Feat/#6
  README.md
  app/(anon)/test/transaction/page.module.css
  app/(anon)/test/transaction/page.tsx
  app/api/real-estate/search/transaction-price/route.ts
  app/globals.css
  backend/realEstate/applications/dtos/GetRealEstateTransactionRequest.ts
  backend/realEstate/applications/dtos/GetRealEstateTransactionResponse.ts
  backend/realEstate/applications/usecases/GetRealEstateTransactionUseCase.ts
  backend/realEstate/domains/Entities/realEstateTransaction.ts
  backend/realEstate/infrastrctures/repositories/RealEstateTransactionRepository.ts
  backend/utils/axiosInstance.ts
  backend/utils/xmlParser.ts
  libs/lawd-codes.ts
  tsconfig.json
Labels: 📞 API, 🔙 Backend, 🧪 Test

#15 Feat/#14
  app/api/naver-news/route.ts
  app/tax-cert/TaxCertForm.tsx
  app/tax-cert/page.tsx
  backend/map/applications/dtos/KakaoSearchResponseDto.ts
  backend/map/applications/dtos/SaveSelectedAddressDto.ts
  backend/map/applications/usecases/SaveSelectedAddressUseCase.ts
  backend/map/applications/usecases/SearchAddressUseCase.ts
  backend/map/domain/repository/KakaoSearchRepository.ts
  backend/map/infrastructure/repository/KakaoSearchRepositoryImpl.ts
  backend/naver-news/applications/dtos/NaverNewsDto.ts
  backend/naver-news/applications/usecases/GetNaverNewsUseCase.ts
  backend/naver-news/domain/repository/NewsRepository.ts
  backend/naver-news/infrastructure/repository/NaverNewsRepository.ts
  package-lock.json
  package.json
Labels: 📞 API, 🔙 Backend, 🔩 Feature

#18 [Feat] BE 시세 API 연결 및 BE 등기부등본 API 리팩토링
  .prettierrc
  app/api/danJi/route.ts
  app/api/housing-price/route.ts
  app/api/real-estate/search/address/route.ts
  app/api/real-estate/search/road-address/route.ts
  app/api/real-estate/search/transaction-price/route.ts
  app/api/real-estate/search/unique-no/route.ts
  app/api/reb-housing-price/route.ts
  app/api/sise/route.ts
  backend/danJi/applications/dtos/DanJiDto.ts
  backend/danJi/applications/usecases/DanJiUseCase.ts
  backend/danJi/domains/entities/DanJiEntity.ts
  backend/danJi/infrastuctures/repositories/DanJiRepository.ts
  backend/realEstate/applications/dtos/RealEstateRequest.ts
  backend/realEstate/applications/dtos/RealEstateResponse.ts
  backend/realEstate/applications/usecases/GetRealEstateDataUseCase.ts
  backend/realEstate/applications/usecases/RealEstateDataUseCase.ts
  backend/realEstate/domains/Entities/RealEstateEntity.ts
  backend/realEstate/infrastrctures/repositories/GetRealEstateDataInfrastructure.ts
  backend/sise/applications/dtos/SiseDto.ts
  backend/sise/applications/usecases/SiseUseCase.ts
  backend/sise/domains/Entities/SiseEntity.ts
  backend/sise/infrastructures/repositories/SiseRepository.ts
  libs/api-endpoints.ts
  utils/codefDecoder.ts
  utils/danJi/danJiExtractor.ts
  utils/danJi/danJiValidator.ts
  utils/sise/siseCalculator.ts
  utils/sise/siseExtractor.ts
  utils/sise/siseValidator.ts
Labels: 🔙 Backend, 🔩 Feature, 🛠️ Refactor

#25 feat: 중개업자 정보 조회 api와 backend 완성
  app/api/broker/route.ts
  backend/brokers/applications/Dtos/GetBrokerDto.ts
  backend/brokers/applications/Dtos/GetBrokerListDto.ts
  backend/brokers/applications/Usecases/GetBrokerUsecase.ts
  backend/brokers/domains/Entities/Broker.ts
  backend/brokers/domains/Repositories/BrokerRepository.ts
  backend/brokers/infrastructures/Repositories/ApiBrokerRepository.ts
  package-lock.json
Labels: 📞 API, 🔙 Backend

#30 [Feat] BE 개별주택/공동주택 공시지가 API 연결
  app/(anon)/_components/common/Navigation.tsx
  app/api/housing-price/route.ts
  app/api/real-estate/search/unique-no/route.ts
  app/api/reb-housing-price/route.ts
  backend/applications/danJi/usecases/DanJiUseCase.ts
  backend/applications/housingPrice/dtos/HousingPriceDto.ts
  backend/applications/housingPrice/usecases/HousingPriceUseCase.ts
  backend/applications/realEstate/dtos/RealEstateResponse.ts
  backend/applications/realEstate/usecases/RealEstateDataUseCase.ts
  backend/applications/rebHousingPrice/dtos/RebHousingPriceDto.ts
  backend/applications/rebHousingPrice/usecases/RebHousingPriceUseCase.ts
  backend/applications/sise/usecases/SiseUseCase.ts
  backend/domain/entities/HousingPriceEntity.ts
  backend/domain/entities/RebHousingPriceEntity.ts
  backend/infrastructure/repository/GetRealEstateDataInfrastructure.ts
  utils/codefDecoder.ts
  utils/danJi/danJiValidator.ts
  utils/sise/siseValidator.ts
Labels: 📞 API, 🔙 Backend, 🔩 Feature, 🛠️ Refactor

#29 feat: 네이버 뉴스 & 카카오 장소/주소 검색 API 연결
  app/api/naver-news/route.ts
  app/api/place/route.ts
  backend/applications/naverNews/usecases/GetNaverNewsUseCase.ts
  backend/applications/place/dtos/PlaceApiDto.ts
  backend/applications/place/dtos/PlaceSearchApiResponseDto.ts
  backend/applications/place/dtos/SelectedPlaceDto.ts
  backend/applications/place/usecases/SaveSelectedAddressUseCase.ts
  backend/applications/place/usecases/SearchPlaceUseCase.ts
  backend/domain/entities/NaverNews.ts
  backend/domain/entities/Place.ts
  backend/domain/repository/NewsRepository.ts
  backend/domain/repository/PlaceRepository.ts
  backend/infrastructure/repository/NewsRepositoryImpl.ts
  backend/infrastructure/repository/PlaceRepositoryImpl.ts
Labels: 📞 API, 🔙 Backend, 🛠️ Refactor

#31 [Bug] 디코딩 되지 않던 버그 해결
  .github/workflows/front_CI.yml
  backend/infrastructure/repository/DanJiRepository.ts
  backend/infrastructure/repository/GetRealEstateDataInfrastructure.ts
  backend/infrastructure/repository/HousingPriceRepository.ts
  backend/infrastructure/repository/RebHousingPriceRepository.ts
  backend/infrastructure/repository/SiseRepository.ts
Labels: 🔙 Backend, 🔨 Fix

#33 feat: PWA 지원을 위한 설정 추가 및 관련 파일 무시 설정
  .gitignore
  app/(anon)/_components/common/PWAInstallPrompt.tsx
  app/(anon)/test/tax-cert/TaxCertForm.module.css
  app/(anon)/test/tax-cert/TaxCertForm.tsx
  app/(anon)/test/tax-cert/TaxCertResultDisplay.module.css
  app/(anon)/test/tax-cert/TaxCertResultDisplay.tsx
  app/(anon)/test/tax-cert/_components/CertificateLoginForm.module.css
  app/(anon)/test/tax-cert/_components/CertificateLoginForm.tsx
  app/(anon)/test/tax-cert/_components/Common.module.css
  app/(anon)/test/tax-cert/_components/IdLoginForm.module.css
  app/(anon)/test/tax-cert/_components/IdLoginForm.tsx
  app/(anon)/test/tax-cert/_components/SimpleAuthForm.module.css
  app/(anon)/test/tax-cert/_components/SimpleAuthForm.tsx
  app/(anon)/test/tax-cert/_components/SimpleAuthModal.module.css
  app/(anon)/test/tax-cert/_components/SimpleAuthModal.tsx
  app/(anon)/test/tax-cert/_components/StepGuide.module.css
  app/(anon)/test/tax-cert/_components/StepGuide.tsx
  app/(anon)/test/tax-cert/page.module.css
  app/(anon)/test/tax-cert/page.tsx
  app/layout.tsx
  app/page.module.css
  app/page.tsx
  next.config.ts
  package-lock.json
  package.json
  public/icons/icon-192x192.svg
  public/icons/icon-512x512.svg
  public/icons/icon.png
  public/manifest.json
Labels: 📞 API, 🔙 Backend

#46 feat : tailwind 설치, 기본 폰트 적용
  .gitignore
  app/globals.css
  app/layout.tsx
  package-lock.json
  package.json
  postcss.config.js
  prisma/generated/edge.js
  prisma/generated/index.js
  tailwind.config.js
Labels: ⚙ Settings, 🎨 Publish, 🖥️ Frontend

#53 feat:#44 step result 관련 api 구현
  app/api/step-result/route.ts
  backend/applications/stepResult/dtos/StepResultDto.ts
  backend/applications/stepResult/usecase/StepResultUseCase.ts
  backend/domain/entities/StepResult.ts
  backend/domain/repository/StepResultRepository.ts
  backend/infrastructure/repository/StepResultRepositoryImpl.ts
  prisma/schema.prisma
Labels: 📞 API, 🔙 Backend, 🔩 Feature

#59 Feat : Splash 화면 구현 + 애니메이션 전환 효과 추가
  app/(anon)/_components/Splash.module.css
  app/(anon)/_components/Splash.tsx
  app/page.tsx
  public/images/Logo.png
Labels: 🎨 Publish, 🔩 Feature, 🖥️ Frontend

#74 refactor: 프리즘 스키마 수정
  prisma/schema.prisma
Labels: 🔙 Backend, 🛠️ Refactor

#76 refactor: #36 실거래가 api 통합 및 테스트 페이지 작성
  app/(anon)/test/detached-house-transaction/page.tsx
  app/(anon)/test/officetel-transaction/page.tsx
  app/(anon)/test/row-house-transaction/page.tsx
  app/(anon)/test/transaction/page.module.css
  app/(anon)/test/transaction/page.tsx
  app/api/transaction/all/route.ts
  app/page.tsx
  backend/applications/transaction/dtos/GetAllTransactionRequest.ts
  backend/applications/transaction/dtos/GetAllTransactionResponse.ts
  backend/applications/transaction/usecases/GetRealEstateTransactionUseCase.ts
  backend/infrastructure/repository/RealEstateTransactionRepository.ts
  utils/dateUtils.ts
Labels: 📞 API, 🔙 Backend, 🔩 Feature, 🛠️ Refactor

#84 revert : revert된 커밋들 복구
  app/(anon)/main/main.module.css
  app/(anon)/main/page.tsx
  app/(anon)/mypage/mypage.module.css
  app/(anon)/mypage/page.tsx
  app/(anon)/onboarding.module.css
  app/(anon)/page.tsx
  app/(anon)/signin/page.tsx
  app/(anon)/signin/signin.module.css
  app/(anon)/signup/page.tsx
  app/(anon)/signup/signup.module.css
  app/(anon)/steps/[step-number]/[detail]/page.tsx
  app/(anon)/steps/[step-number]/[detail]/stepDetail.module.css
  app/(anon)/steps/[step-number]/page.tsx
  app/(anon)/steps/[step-number]/stepNumber.module.css
  app/(anon)/steps/page.tsx
  app/(anon)/steps/steps.module.css
  app/(anon)/test/api-test/page.module.css
  app/(anon)/test/api-test/page.tsx
  app/(anon)/test/page.tsx
  app/(anon)/test/transaction-ranking/page.module.css
  app/(anon)/test/transaction-ranking/page.tsx
  app/api/danJi-serial-number/route.ts
  app/api/transaction-detail-apart/route.ts
  app/api/transaction-detail-single/route.ts
  app/test/actual-transaction/page.module.css
  app/test/complex-serial-number/page.module.css
  app/test/complex-serial-number/page.tsx
  backend/applications/danJiSerialNumber/dtos/DanJiSerialNumberRequest.ts
  backend/applications/danJiSerialNumber/dtos/DanJiSerialNumberResponse.ts
  backend/applications/danJiSerialNumber/usecases/DanJiSerialNumberUseCase.ts
  backend/applications/transactionDetailApart/dtos/TransactionDetailApartRequest.ts
  backend/applications/transactionDetailApart/dtos/TransactionDetailApartResponse.ts
  backend/applications/transactionDetailApart/usecases/TransactionDetailApartUseCase.ts
  backend/applications/transactionDetailSingle/dtos/TransactionDetailSingleRequest.ts
  backend/applications/transactionDetailSingle/dtos/TransactionDetailSingleResponse.ts
  backend/applications/transactionDetailSingle/usecases/TransactionDetailSingleUseCase.ts
  backend/domain/entities/DanJiSerialNumber.ts
  backend/domain/entities/TransactionDetailApart.ts
  backend/domain/entities/TransactionDetailSingle.ts
  backend/domain/repository/DanJiSerialNumberRepository.ts
  backend/domain/repository/TransactionDetailApartRepository.ts
  backend/domain/repository/TransactionDetailSingleRepository.ts
  backend/infrastructure/mappers/TransactionDetailApartMapper.ts
  backend/infrastructure/mappers/TransactionDetailSingleMapper.ts
  backend/infrastructure/repository/DanJiSerialNumberRepositoryImpl.ts
  backend/infrastructure/repository/TransactionDetailApartRepositoryImpl.ts
  backend/infrastructure/repository/TransactionDetailSingleRepositoryImpl.ts
  libs/api-endpoints.ts
  package-lock.json
  package.json
Labels: 📞 API, 🔙 Backend, 🔩 Feature, 🛠️ Refactor

#100 feat: #75 step_result updated_at 사용
  backend/domain/entities/StepResult.ts
  backend/infrastructure/repository/StepResultRepositoryImpl.ts
  prisma/schema.prisma
Labels: 📞 API, 🔙 Backend, 🔩 Feature, 🛠️ Refactor

#105 Refactor : 실거래가 불필요한 entity 구조 삭제
  README.md
  app/(anon)/_components/common/forms/Field.tsx
  backend/domain/entities/realEstateTransaction.ts
Labels: 🛠️ Refactor

#109 Feat utils 함수 추가 수정
  app/(anon)/mypage/_components/GuideResultSummary.styles.ts
  app/(anon)/mypage/_components/GuideResultSummary.tsx
  app/api/copies/real-estate/route.ts
  app/api/copies/tax-cert/route.ts
  app/api/real-estate/exists/route.ts
  app/api/real-estate/search/address/route.ts
  app/api/real-estate/search/road-address/route.ts
  app/api/real-estate/search/unique-no/route.ts
  app/api/tax-cert/exists/route.ts
  app/api/tax-cert/route.ts
  utils/userAddress.ts
Labels: 🔙 Backend

#111 feat: #92 공통 뱃지 컴포넌트 작성
  app/(anon)/_components/common/circular-icon-badges/CircularIconBadge.styles.ts
  app/(anon)/_components/common/circular-icon-badges/CircularIconBadge.tsx
  app/(anon)/steps/[step-number]/_components/StepDetail.tsx
  app/(anon)/steps/[step-number]/_components/TextBadge.styles.ts
  app/(anon)/steps/[step-number]/_components/TextBadge.tsx
  app/(anon)/test/style-badges/page.tsx
  app/(anon)/test/style-text-badges/page.tsx
  app/globals.css
  package-lock.json
  package.json
  tsconfig.json
Labels: 🔩 Feature, 🖥️ Frontend

#113 feat: 단계 결과 요약 컴포넌트 구현
  app/(anon)/mypage/_components/GuideResultSummary.styles.ts
  app/(anon)/mypage/_components/GuideResultSummary.tsx
  app/(anon)/mypage/page.tsx
  app/globals.css
  package-lock.json
  package.json
  tailwind.config.js
Labels: 🎨 Publish, 🔩 Feature, 🖥️ Frontend

#118 Feat : 주소 드롭다운 구현
  app/(anon)/_components/common/addressDropDown/AddressDropDown.styles.ts
  app/(anon)/_components/common/addressDropDown/AddressDropDown.tsx
  app/(anon)/_components/common/addressDropDown/AddressDropDownItem.tsx
  app/(anon)/_components/common/addressDropDown/AddressDropDownList.tsx
  app/(anon)/_components/common/addressDropDown/index.ts
  app/(anon)/_components/common/addressDropDown/types.ts
  app/(anon)/test/address-dropdown/page.tsx
  app/globals.css
  package-lock.json
  package.json
  utils/addressUtils.ts
Labels: 🎨 Publish, 🔩 Feature, 🖥️ Frontend

#120 Feat : 소분류 페이지 URL 라우팅으로 표시되게끔 변경
  app/(anon)/@detail/[step-number]/[detail]/StepDetail.styles.ts
  app/(anon)/@detail/[step-number]/[detail]/StepDetail.tsx
  app/(anon)/@detail/[step-number]/[detail]/TextBadge.styles.ts
  app/(anon)/@detail/[step-number]/[detail]/TextBadge.tsx
  app/(anon)/@detail/[step-number]/[detail]/hooks/index.ts
  app/(anon)/@detail/[step-number]/[detail]/hooks/useDragToClose.ts
  app/(anon)/@detail/[step-number]/[detail]/hooks/useExpandable.ts
  app/(anon)/@detail/[step-number]/[detail]/hooks/useStepDetail.ts
  app/(anon)/_components/common/addressDropDown/AddressDropDown.styles.ts
  app/(anon)/_components/common/modal/index.ts
  app/(anon)/steps/[step-number]/_components/StepDetail.tsx
  app/(anon)/steps/[step-number]/page.tsx
  app/(anon)/test/modal-test/page.tsx
  app/@detail/default.tsx
Labels: 🎨 Publish, 🔩 Feature, 🖥️ Frontend

#123 refactor: #115 원형 뱃지 컴포넌트 추가 수정 적용
  app/(anon)/@detail/[step-number]/[detail]/TextBadge.styles.ts
  app/(anon)/_components/common/circular-icon-badges/CircularIconBadge.styles.ts
  app/(anon)/_components/common/circular-icon-badges/CircularIconBadge.tsx
  app/(anon)/mypage/_components/GuideResultSummary.styles.ts
  app/(anon)/mypage/_components/GuideResultSummary.tsx
  app/(anon)/test/style-badges/page.tsx
  app/(anon)/test/style-text-badges/page.tsx
Labels: 🎨 Publish, 🛠️ Refactor

#133 Refactor : 페이지 라우팅에 [user-address-nickname] 추가
  app/(anon)/@detail/[step-number]/[detail]/StepDetail.styles.ts
  app/(anon)/@detail/[step-number]/[detail]/StepDetail.tsx
  app/(anon)/@detail/[step-number]/[detail]/hooks/index.ts
  app/(anon)/@detail/[step-number]/[detail]/hooks/useStepDetail.ts
  app/(anon)/@detail/[user-address-nickname]/steps/[step-number]/[detail]/StepDetail.styles.ts
  app/(anon)/@detail/[user-address-nickname]/steps/[step-number]/[detail]/StepDetail.tsx
  app/(anon)/@detail/[user-address-nickname]/steps/[step-number]/[detail]/components/ModalContent.tsx
  app/(anon)/@detail/[user-address-nickname]/steps/[step-number]/[detail]/components/ModalDragHandle.tsx
  app/(anon)/@detail/[user-address-nickname]/steps/[step-number]/[detail]/hooks/useDragToClose.ts
  app/(anon)/@detail/[user-address-nickname]/steps/[step-number]/[detail]/hooks/useExpandable.ts
  app/(anon)/@detail/[user-address-nickname]/steps/[step-number]/[detail]/hooks/useGetStepDetail.ts
  app/(anon)/@detail/default.tsx
  app/(anon)/[user-address-nickname]/steps/[step-number]/_components/TextBadge.styles.ts
  app/(anon)/[user-address-nickname]/steps/[step-number]/_components/TextBadge.tsx
  app/(anon)/[user-address-nickname]/steps/[step-number]/page.styles.ts
  app/(anon)/[user-address-nickname]/steps/[step-number]/page.tsx
  app/(anon)/[user-address-nickname]/steps/page.tsx
  app/(anon)/[user-address-nickname]/steps/steps.module.css
  app/(anon)/layout.tsx
  app/(anon)/test/style-text-badges/page.tsx
  app/layout.tsx
  app/providers.tsx
  package-lock.json
  package.json
Labels: 🖥️ Frontend, 🛠️ Refactor

#146 feat: 책 텍스처 이미지 업데이트 (#138)
  public/models/book/textures/book1_baseColor.png
  public/models/book/textures/book2_baseColor.png
  public/models/book/textures/book3_baseColor.png
  public/models/book/textures/book4_baseColor.png
  public/models/book/textures/book5_baseColor.png
  public/models/book/textures/book6_baseColor.png
  public/models/book/textures/book7_baseColor.png
  public/models/book/textures/book_baseColor.png
Labels: 🎨 Publish, 🛠️ Refactor

#160 feat: 대시보드 컴포넌트 구현
  .gitignore
  app/(anon)/_components/common/addressDropDown/AddressDropDown.styles.ts
  app/(anon)/_components/common/addressDropDown/AddressDropDown.tsx
  app/(anon)/_components/common/addressDropDown/AddressDropDownItem.styles.ts
  app/(anon)/_components/common/addressDropDown/AddressDropDownItem.tsx
  app/(anon)/_components/common/addressDropDown/AddressDropDownList.styles.ts
  app/(anon)/_components/common/addressDropDown/AddressDropDownList.tsx
  app/(anon)/_components/common/guideStepContent/GuideStepContent.styles.ts
  app/(anon)/_components/common/guideStepContent/GuideStepContent.tsx
  app/(anon)/_components/common/guideStepContent/GuideStepRow.styles.ts
  app/(anon)/_components/common/guideStepContent/GuideStepRow.tsx
  app/(anon)/_components/common/guideStepContent/GuideStepStyles.ts
  app/(anon)/_components/common/guideStepContent/GuideStepText.styles.ts
  app/(anon)/_components/common/guideStepContent/GuideStepText.tsx
  app/(anon)/_components/common/profile/Profile.tsx
  app/(anon)/_components/dashboard/DashboardHeader.styles.ts
  app/(anon)/_components/dashboard/DashboardHeader.tsx
  app/(anon)/_components/dashboard/HambugiDashboard.styles.ts
  app/(anon)/_components/dashboard/HambugiDashboard.tsx
  app/(anon)/_components/dashboard/StepDetailContent.styles.ts
  app/(anon)/_components/dashboard/StepDetailContent.tsx
  app/(anon)/_components/dashboard/StepNavigation.styles.ts
  app/(anon)/_components/dashboard/StepNavigation.tsx
  app/(anon)/_components/dashboard/UserInfo.styles.ts
  app/(anon)/_components/dashboard/UserInfo.tsx
  app/(anon)/_components/onboarding/RootFlow.tsx
  app/(anon)/main/_components/AuthLanding.tsx
  app/(anon)/signin/page.tsx
  app/(anon)/signup/_components/SignupForm.tsx
  app/(anon)/signup/page.tsx
  app/(anon)/steps/_components/BookLayout.styles.ts
  app/(anon)/steps/_components/BookLayout.tsx
  app/(anon)/test/address-dropdown/page.tsx
  app/(anon)/test/hambugi-dashboard/page.styles.ts
  app/(anon)/test/hambugi-dashboard/page.tsx
  app/(anon)/test/storetest/page.tsx
  libs/store/userStore.ts
  libs/stores/modalStore.ts
  libs/stores/rootStepStore.ts
  libs/stores/userAddresses/userAddressStore.ts
  libs/stores/userStore.ts
Labels: 🎨 Publish, 🔩 Feature, 🖥️ Frontend

#165 refactor : 로그인, 회원가입 관련 refactoring
  app/(anon)/_components/common/button/Button.module.css
  app/(anon)/_components/common/button/Button.styles.ts
  app/(anon)/_components/common/button/Button.tsx
  app/(anon)/_components/common/forms/Field.tsx
  app/(anon)/_components/common/forms/Forms.module.css
  app/(anon)/_components/common/forms/Forms.styles.ts
  app/(anon)/_components/common/forms/OtpInput.tsx
  app/(anon)/_components/common/forms/PasswordInput.tsx
  app/(anon)/_components/common/forms/TextInput.tsx
  app/(anon)/_components/common/header/Header.style.ts
  app/(anon)/_components/common/header/Header.styles.ts
  app/(anon)/_components/common/header/Header.tsx
  app/(anon)/_components/common/profile/Profile.tsx
  app/(anon)/_components/onboarding/AuthLanding.module.css
  app/(anon)/_components/onboarding/AuthLanding.styles.ts
  app/(anon)/_components/onboarding/AuthLanding.tsx
  app/(anon)/_components/onboarding/HomeMain.tsx
  app/(anon)/_components/onboarding/Onboarding.module.css
  app/(anon)/_components/onboarding/Onboarding.styles.ts
  app/(anon)/_components/onboarding/Onboarding.tsx
  app/(anon)/_components/onboarding/RootFlow.tsx
  app/(anon)/_components/onboarding/Splash.module.css
  app/(anon)/_components/onboarding/Splash.styles.ts
  app/(anon)/_components/onboarding/Splash.tsx
  app/(anon)/signin/Signin.module.css
  app/(anon)/signin/Signin.styles.ts
  app/(anon)/signin/_components/SigninForm.tsx
  app/(anon)/signin/page.tsx
  app/(anon)/signup/Signup.module.css
  app/(anon)/signup/Signup.styles.ts
  app/(anon)/signup/_components/SignupForm.tsx
  app/(anon)/signup/page.tsx
  app/(anon)/test/page.tsx
  app/api/auth/[...nextauth]/authOptions.ts
  app/api/auth/check-nickname/route.ts
  app/api/auth/signup/route.ts
  app/layout.tsx
  app/page.styles.ts
  middleware.ts
Labels: 🛠️ Refactor

#176 feat: 라디오 버튼 그룹 및 라디오 버튼 컴포넌트 추가
  app/(anon)/_components/common/radioButtonGroup/RadioButton.styles.ts
  app/(anon)/_components/common/radioButtonGroup/RadioButton.tsx
  app/(anon)/_components/common/radioButtonGroup/RadioButtonGroup.styles.ts
  app/(anon)/_components/common/radioButtonGroup/RadioButtonGroup.tsx
  app/(anon)/test/radio-button-group-test/page.tsx
Labels: 🔩 Feature, 🖥️ Frontend

#190 refactor: naming을 stepNumber 및 detail 필드로 변경, 관련 로직 수정
  app/api/step-results/route.ts
  backend/applications/stepResults/dtos/StepResultDto.ts
  backend/applications/stepResults/usecases/StepResultUsecase.ts
  backend/domain/entities/StepResult.ts
  backend/domain/repository/StepResultRepository.ts
  backend/infrastructure/repository/StepResultRepositoryImpl.ts
Labels: 📞 API, 🔙 Backend, 🛠️ Refactor

#187 bug : 메인 페이지 주소 상태 데이터 관련 버그 수정
  app/(anon)/_components/common/addressDropDown/AddressDropDown.tsx
  app/(anon)/_components/common/addressDropDown/AddressDropDownItem.styles.ts
  app/(anon)/_components/common/addressDropDown/AddressDropDownItem.tsx
  app/(anon)/_components/common/addressDropDown/AddressDropDownList.tsx
  app/(anon)/main/_components/hooks/useMainPageModule.ts
  app/(anon)/main/_components/kakaoMapModule/KakaoMapModule.tsx
  app/(anon)/main/_components/tabContainer/AddressConfirmationTab.tsx
  app/(anon)/main/_components/tabContainer/TabContainer.tsx
  app/(anon)/main/_components/tabContainer/TransactionSearchTab.tsx
  app/(anon)/main/_components/topSection/TopSection.tsx
  app/(anon)/main/_components/transactionList/TransactionList.styles.ts
  app/(anon)/main/_components/transactionList/TransactionList.tsx
  app/(anon)/main/_components/types/mainPage.types.ts
  app/(anon)/main/page.tsx
  backend/domain/entities/TransactionDetailApart.ts
  backend/infrastructure/mappers/TransactionDetailApartMapper.ts
  hooks/main/useAddressInfo.ts
  hooks/main/useAddressManagement.ts
  hooks/main/useAddressSearch.ts
  hooks/main/useDaumPostcode.ts
  hooks/main/useGeolocation.ts
  hooks/main/useKakaoMap.ts
  hooks/main/useKakaoMapMarkers.ts
  hooks/main/useKakaoMarker.ts
  hooks/main/useLocationManager.ts
  hooks/main/useMainPageModule.ts
  hooks/main/useMainPageState.ts
  hooks/main/useMapManagement.ts
  hooks/main/useTabManagement.ts
  hooks/main/useTransactionData.ts
  hooks/main/useTransactionDetail.ts
  hooks/main/useTransactionManagement.ts
  hooks/useUserAddresses.ts
  libs/api_front/transactionDetail.api.ts
  libs/codef/codefConfig.ts
  libs/stores/userAddresses/useUserAddresses.ts
  libs/stores/userAddresses/userAddressStore.ts
  utils/main/addressUtils.ts
  utils/main/mapUtils.ts
  utils/main/tabUtils.ts
  utils/main/transactionUtils.ts
Labels: 🔨 Fix, 🖥️ Frontend, 🛠️ Refactor

#198 feat: 납세증명서 pdf 가져오기 구현
  app/(anon)/test/broker-test/page.tsx
  app/(anon)/test/tax-cert/TaxCertForm.tsx
  app/(anon)/test/tax-cert/TaxCertResultDisplay.module.css
  app/(anon)/test/tax-cert/TaxCertResultDisplay.tsx
  app/(anon)/test/tax-cert/_components/PdfViewer.tsx
  app/api/copies/broker/route.ts
  app/api/tax-cert/route.ts
  backend/applications/taxCert/usecases/GetTaxCertUsecase.ts
Labels: 🔙 Backend

#210 Feat : 전세가이드 플로팅 버튼 및 6-1 단계 콘텐츠 시스템 구현
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/ModalContent.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/TextOnly.styles.ts
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/TextOnly.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/data/step-4-2-contents.json
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/data/step-4-4-contents.json
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/data/step-6-1-contents.json
  app/(anon)/_components/common/header/Header.styles.ts
  app/(anon)/_components/common/header/Header.tsx
  app/(anon)/_components/dashboard/HambugiDashboard.styles.ts
  app/(anon)/main/_components/floatingButton/FloatingButton.styles.ts
  app/(anon)/main/_components/floatingButton/FloatingButton.tsx
  app/(anon)/main/_components/topSection/TopSection.styles.ts
  app/(anon)/main/_components/topSection/TopSection.tsx
  app/(anon)/main/main.styles.ts
  app/(anon)/main/page.tsx
  app/(anon)/steps/[step-number]/page.styles.ts
  app/(anon)/steps/_components/GeneralPage.tsx
Labels: 🔨 Fix, 🖥️ Frontend, 🛠️ Refactor

#222 feat: 소단계 1-2단계 내용 및 라디오 버튼 그룹 페이지 컴포넌트 구현
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/ModalContent.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/RadioGroup.styles.ts
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/RadioGroup.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/TextOnly.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/data/step-1-2-contents.json
  app/(anon)/_components/common/radioButtonGroup/RadioButton.styles.ts
  app/(anon)/_components/common/radioButtonGroup/RadioButtonGroup.tsx
  app/(anon)/_components/dashboard/StepNavigation.tsx
  app/(anon)/mypage/_components/GuideResultView.tsx
  app/(anon)/mypage/_data/mockData.ts
  app/(anon)/test/api-test/page.tsx
  app/(anon)/test/circular-icon-step-test/page.tsx
  utils/stepUrlParser.ts
Labels: 🔩 Feature, 🖥️ Frontend

#247 Feat : 7단계 소단계 작성
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/ModalContent.styles.ts
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/ModalContent.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/CheckListGroup.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/CombinedContent.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/RadioGroup.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/TextOnly.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/data/step-7-1-contents.json
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/data/step-7-2-contents.json
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/types.ts
  app/(anon)/_components/common/forms/Forms.styles.ts
  app/(anon)/_components/common/forms/OtpInput.tsx
  app/(anon)/_components/common/forms/PasswordInput.tsx
  app/(anon)/_components/common/modal/ConfirmModal.tsx
  app/(anon)/_components/common/taxCert/TaxCertResultDisplay.tsx
  app/(anon)/main/_components/floatingButton/FloatingButton.styles.ts
  app/(anon)/signup/Signup.styles.ts
  app/(anon)/signup/_components/SignupForm.tsx
  app/(anon)/steps/[step-number]/page.styles.ts
  app/(anon)/steps/[step-number]/page.tsx
  app/api/step-results/route.ts
  backend/applications/stepResults/usecases/StepResultUsecase.ts
  utils/userAddress.ts
Labels: 📞 API, 🔩 Feature, 🖥️ Frontend

#268 Fix : 라디오버튼 그룹 message 표출 로직 오류
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/RadioGroup.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/data/step-1-4-contents.json
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/data/step-7-1-contents.json
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/data/step-7-2-contents.json
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/types.ts
Labels: 🔨 Fix

#269 Feat: 메인페이지 버그수정, 리팩토링/#260
  app/(anon)/_components/common/addressDropDown/AddressDropDown.tsx
  app/(anon)/_components/common/addressDropDown/AddressDropDownList.tsx
  app/(anon)/_components/common/modal/ConfirmModal.styles.ts
  app/(anon)/_components/common/modal/ConfirmModal.tsx
  app/(anon)/_components/common/modal/DanjiSerialNumberContent.tsx
  app/(anon)/main/_components/daumPostcodeModal/DaumPostcodeModal.tsx
  app/(anon)/main/_components/tabContainer/AddressConfirmationTab.tsx
  app/(anon)/main/_components/tabContainer/TransactionSearchTab.tsx
  app/(anon)/main/_components/transactionList/TransactionList.styles.ts
  app/(anon)/main/_components/transactionSearchModal/TransactionSearchModal.tsx
  app/api/user-address/route.ts
  backend/applications/users/dtos/DeleteUserAddressDto.ts
  backend/applications/users/usecases/DeleteUserAddressUsecase.ts
  backend/domain/entities/TaxCert.ts
  backend/domain/repository/DeleteUserAddressRepository.ts
  backend/infrastructure/repository/DeleteUserAddressRepositoryImpl.ts
  hooks/main/useAddressManagement.ts
  hooks/main/useAddressSearch.ts
  hooks/main/useDaumPostcode.ts
  hooks/main/useMainPageModule.ts
  hooks/main/useTransactionManagement.ts
  libs/api_front/userAddress.api.ts
  libs/stores/userAddresses/userAddressStore.ts
  utils/main/addressUtils.ts
  utils/prisma.ts
Labels: 🔨 Fix, 🖥️ Frontend, 🛠️ Refactor

#285 Feat: 마이페이지, 대시보드api연결, 드랍다운컴포넌트, 확인모달 변경, pwa설치/#271
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/CheckListGroup.styles.ts
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/CheckListGroup.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/RadioGroup.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/TextOnly.tsx
  app/(anon)/_components/common/JeonseGuarantee/JeonseGuarantee.tsx
  app/(anon)/_components/common/JeonseGuarantee/JeonseGuaranteeForm.styles.ts
  app/(anon)/_components/common/JeonseGuarantee/JeonseGuaranteeForm.tsx
  app/(anon)/_components/common/PWAInstallPrompt.styles.ts
  app/(anon)/_components/common/PWAInstallPrompt.tsx
  app/(anon)/_components/common/addressDropDown/AddressDropDown.tsx
  app/(anon)/_components/common/addressDropDown/_components/LoadingState.tsx
  app/(anon)/_components/common/dropdown/DropDown.styles.ts
  app/(anon)/_components/common/dropdown/DropDown.tsx
  app/(anon)/_components/common/forms/FormSelect.styles.ts
  app/(anon)/_components/common/forms/FormSelect.tsx
  app/(anon)/_components/common/modal/ConfirmModal.tsx
  app/(anon)/_components/common/realEstate/realEstateInput/RealEstateInput.tsx
  app/(anon)/_components/dashboard/HambugiDashboard.styles.ts
  app/(anon)/_components/dashboard/HambugiDashboard.tsx
  app/(anon)/_components/onboarding/Onboarding.tsx
  app/(anon)/main/_components/kakaoMapModule/KakaoMapModule.styles.ts
  app/(anon)/main/_components/kakaoMapModule/KakaoMapModule.tsx
  app/(anon)/main/_components/legacy/searchSection/SearchSection.tsx
  app/(anon)/main/_components/tabContainer/AddressConfirmationTab.tsx
  app/(anon)/main/_components/tabContainer/TransactionSearchTab.tsx
  app/(anon)/main/_components/transactionList/TransactionList.styles.ts
  app/(anon)/main/_components/transactionList/TransactionList.tsx
  app/(anon)/main/_components/transactionSearchModal/TransactionSearchModal.tsx
  app/(anon)/mypage/_components/GuideResultView.tsx
  app/(anon)/mypage/_data/mockData.ts
  app/(anon)/mypage/page.styles.ts
  app/(anon)/mypage/page.tsx
  app/(anon)/real-estate-data/_components/pageContent/PageContent.tsx
  app/(anon)/real-estate-data/page.tsx
  app/(anon)/test/circular-icon-step-test/page.tsx
  app/(anon)/test/dropdown/page.tsx
  app/(anon)/test/step-results-api-test/page.tsx
  app/globals.css
  app/layout.tsx
  backend/applications/taxCert/usecases/GetTaxCertUsecase.ts
  backend/infrastructure/repository/AddUserAddressRepositoryImpl.ts
  backend/infrastructure/repository/JeonseGuaranteeRepositoryImpl.ts
  backend/infrastructure/repository/RealEstateTransactionRepository.ts
  hooks/useRealEstateInput.ts
  hooks/useStepResultMutations.ts
  hooks/useStepResultQueries.ts
  hooks/useStepResults.ts
  libs/api_front/axiosInstance.ts
  libs/api_front/stepResultQueries.api.ts
  libs/api_front/stepResults.api.ts
  libs/api_front/taxCertCopy.api.ts
  middleware.ts
  types/kakao-maps.d.ts
  utils/main/transactionDetailUtils.ts
Labels: 🎨 Publish, 🔨 Fix, 🔩 Feature, 🖥️ Frontend, 🛠️ Refactor

#305 Feat: 소단계 오류 수정, 리팩토링/#289
  app/(anon)/@detail/steps/[step-number]/[detail]/StepDetail.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/ModalContent.styles.ts
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/ModalContent.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/CombinedContent.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/JeonseGuaranteeContainer.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/JeonseGuaranteeInput.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/JeonseGuaranteeOutput.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/List.styles.ts
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/List.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/Step5Detail3Renderer.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/Table.styles.ts
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/Table.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/TaxCertIntro.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/TaxCertWrapper.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/TextOnly.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/data/step-1-5-contents.json
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/data/step-5-1-contents.json
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/data/step-5-3-contents.json
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/types.ts
  app/(anon)/_components/common/JeonseGuarantee/JeonseGuarantee.tsx
  app/(anon)/_components/common/JeonseGuarantee/JeonseGuaranteeForm.tsx
  app/(anon)/_components/common/PWAInstallPrompt.tsx
  app/(anon)/_components/common/realEstate/riskAssessmentDisplay/RiskAssessmentDisplay.tsx
  app/(anon)/_components/common/realEstate/riskAssessmentDisplay/RiskAssessmentSaveButton.tsx
  app/(anon)/_components/common/taxCert/taxCertOutput/TaxCertOutput.tsx
  app/(anon)/_components/dashboard/HambugiDashboard.tsx
  app/(anon)/mypage/page.tsx
  app/(anon)/steps/[step-number]/page.tsx
  app/(anon)/steps/[step-number]/stepData/5.json
  backend/applications/jeonseGuarantees/usecases/GetJeonseGuaranteeUsecase.ts
  backend/applications/stepResults/usecases/StepResultUsecase.ts
  backend/infrastructure/repository/JeonseGuaranteeRepositoryImpl.ts
  hooks/useJeonseGuarantee.ts
  hooks/useStepResults.ts
  hooks/useTaxCertRiskAssessment.ts
  libs/api_front/jeonseGuarantee.api.ts
  libs/stores/riskAssessmentStore.ts
  utils/constants/jeonseGuarantee.ts
  utils/formatUtils.ts
Labels: 🔩 Feature, 🖥️ Frontend, 🛠️ Refactor

#315 fix: 마이페이지 차트 오류 해결결
  app/(anon)/mypage/_components/GuideResultSummary.tsx
  app/(anon)/mypage/page.tsx
Labels: 🔨 Fix

#309 refactor : 자잘한 내용 수정
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/ModalContent.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/CheckListGroup.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/JeonseGuaranteeInput.styles.ts
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/JeonseGuaranteeInput.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/JeonseGuaranteeOutput.styles.ts
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/JeonseGuaranteeOutput.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/RadioGroup.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/Step5Detail3Renderer.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/TaxCertIntro.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/TextOnly.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/data/step-1-5-contents.json
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/data/step-5-1-contents.json
  app/(anon)/_components/common/addressDropDown/AddressDropDown.styles.ts
  app/(anon)/_components/common/addressDropDown/AddressDropDownItem.styles.ts
  app/(anon)/_components/common/realEstate/realEstateTwoWayContent/RealEstateTwoWayContent.tsx
  app/(anon)/_components/common/taxCert/TaxCertInput.tsx
  app/(anon)/_components/common/taxCert/taxCertOutput/TaxCertOutput.tsx
  app/(anon)/main/_components/tabContainer/AddressConfirmationTab.styles.ts
  app/(anon)/main/_components/tabContainer/AddressConfirmationTab.tsx
  app/(anon)/main/_components/tabContainer/TabContainer.styles.ts
  app/(anon)/main/_components/topSection/TopSection.styles.ts
Labels: 🖥️ Frontend, 🛠️ Refactor

#318 feat: 5-3 소단게 구조 개선
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/ModalContent.styles.ts
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/ModalContent.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/CombinedContent.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/JeonseGuaranteeInput.styles.ts
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/JeonseGuaranteeInput.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/List.styles.ts
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/List.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/RadioGroup.styles.ts
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/RadioGroup.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/Step5Detail3Renderer.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/data/step-1-6-contents.json
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/data/step-5-3-contents.json
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/types.ts
Labels: 🖥️ Frontend, 🛠️ Refactor

#332 refactor : 납세증명서 버그 수정
  app/(anon)/@detail/steps/[step-number]/[detail]/StepDetail.styles.ts
  app/(anon)/@detail/steps/[step-number]/[detail]/StepDetail.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/ModalContent.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/CheckListGroup.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/CombinedContent.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/JeonseGuaranteeContainer.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/JeonseGuaranteeInput.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/Step5Detail3Renderer.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/TaxCertWrapper.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/data/step-5-1-contents.json
  app/(anon)/_components/common/realEstate/riskAssessmentDisplay/RiskAssessmentDisplay.tsx
  app/(anon)/_components/common/taxCert/TaxCertInput.tsx
  app/(anon)/_components/common/taxCert/taxCertContainer/TaxCertContainer.tsx
  app/(anon)/_components/common/taxCert/taxCertOutput/TaxCertOutput.tsx
  app/(anon)/main/_components/tabContainer/AddressConfirmationTab.tsx
  hooks/useTaxCert.ts
  hooks/useTaxCertContainer.ts
  hooks/useTaxCertOutput.ts
  libs/constants/taxCertConstants.ts
  public/images/5-1.png
Labels: 🔨 Fix, 🔩 Feature, 🖥️ Frontend, 🛠️ Refactor

#333 feat: 5-4단계 추가
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/data/step-5-4-contents.json
  app/(anon)/main/_components/tabContainer/TabContainer.styles.ts
  backend/infrastructure/repository/AddUserAddressRepositoryImpl.ts
Labels: 🖥️ Frontend

#336 fix: 하단 여백 추가
  app/(anon)/_components/common/transactionSearch/TransactionSearchComponent.styles.ts
  app/(anon)/_components/common/transactionSearch/TransactionSearchComponent.tsx
Labels: 🔨 Fix, 🖥️ Frontend

#343 feat : 자잘한 오류 수정
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/TaxCertIntro.tsx
  app/(anon)/_components/common/header/Header.tsx
  app/(anon)/_components/common/realEstate/realEstateInput/RealEstateInput.tsx
  app/(anon)/_components/common/realEstate/riskAssessmentDisplay/RiskAssessmentDisplay.tsx
  app/(anon)/_components/common/taxCert/taxCertOutput/TaxCertOutput.tsx
  app/(anon)/_components/dashboard/HambugiDashboard.tsx
  app/(anon)/main/_components/tabContainer/AddressConfirmationTab.tsx
  hooks/main/useAddressManagement.ts
  hooks/main/useMainPageModule.ts
  libs/api_front/stepResultQueries.api.ts
  libs/stores/userAddresses/userAddressStore.ts
Labels: 🔨 Fix, 🔩 Feature, 🖥️ Frontend, 🛠️ Refactor

#347 refactor : 빌드 오류 해결
  app/(anon)/_components/common/realEstate/originalDocumentButton/OriginalDocumentButton.tsx
  app/(anon)/_components/common/realEstate/riskAssessmentDisplay/RiskAssessmentDisplay.tsx
Labels: 🔨 Fix, 🛠️ Refactor
