Repository FRONT-END-BOOTCAMP-PLUS-5/BoGam, pull requests merged in 2025-09, with the labels that each got.

#350 Feat : CODEF API 키 갱신
  libs/codef/codefConfig.ts
Labels: 📞 API

#351 Feat : CODEF API 키 갱신 (#350)
  libs/codef/codefConfig.ts
Labels: 📞 API

#382 feat: 프리즈마 스키마 변경 및 관련 backend 파일 수정
  backend/applications/users/dtos/UserAddressDto.ts
  backend/applications/users/dtos/UserDto.ts
  backend/domain/entities/User.ts
  backend/infrastructure/mappers/AddressMapper.ts
  backend/infrastructure/mappers/AuthMapper.ts
  backend/infrastructure/repository/AddUserAddressRepositoryImpl.ts
  backend/infrastructure/repository/GetUserAddressesRepositoryImpl.ts
  backend/infrastructure/repository/UserRepositoryImpl.ts
  prisma/schema.prisma
Labels: 🔙 Backend, 🔩 Feature, 🛠️ Refactor

#405 refactor : 마이 페이지를 메인 페이지로 이동 및 주소 관련 로직 수정
  app/(anon)/_components/common/transactionSearch/TransactionSearchComponent.tsx
  app/(anon)/main/_components/MainPageComponent.tsx
  app/(anon)/main/_components/daumPostcodeModal/DaumPostcodeModal.tsx
  app/(anon)/main/_components/guideResults/GuideResultsContainer.tsx
  app/(anon)/main/_components/guideResults/guideResultSummary/GuideResultSummary.styles.ts
  app/(anon)/main/_components/guideResults/guideResultSummary/GuideResultSummary.tsx
  app/(anon)/main/_components/guideResults/guideResultView/GuideResultView.styles.ts
  app/(anon)/main/_components/guideResults/guideResultView/GuideResultView.tsx
  app/(anon)/main/_components/guideResults/resultAccordion/ResultAccordion.styles.ts
  app/(anon)/main/_components/guideResults/resultAccordion/ResultAccordion.tsx
  app/(anon)/main/_components/tabContainer/AddressConfirmationTab.styles.ts
  app/(anon)/main/_components/tabContainer/AddressConfirmationTab.tsx
  app/(anon)/main/_components/topSection/TopSection.tsx
  app/(anon)/main/main.styles.ts
  app/(anon)/main/page.tsx
  app/(anon)/mypage/page.tsx
  hooks/main/useAddressManagement.ts
  hooks/main/useDaumPostcode.ts
  hooks/main/useLocationManager.ts
  hooks/main/useMainPageModule.ts
  hooks/main/useMainPageState.ts
  hooks/main/useTransactionData.ts
  hooks/main/useTransactionDetail.ts
  hooks/main/useTransactionManagement.ts
  hooks/useMainPage.ts
  hooks/useStepResultQueries.ts
  hooks/useUserAddresses.ts
  libs/constants/addressConstants.ts
  libs/stores/transactionData/transactionDataStore.ts
  libs/stores/userAddresses/userAddressStore.ts
  utils/addressInputUtils.ts
  utils/main/addressUtils.ts
  utils/main/transactionDetailUtils.ts
  utils/userAddressUtils.ts
Labels: 🔨 Fix, 🔩 Feature, 🖥️ Frontend, 🛠️ Refactor

#407 feat : 주소 정보 수정 기능 구현
  app/(anon)/_components/common/broker/brokerOutput/BrokerOutput.tsx
  app/(anon)/main/_components/tabContainer/AddressConfirmationTab.tsx
  app/api/user-address/route.ts
  backend/applications/users/dtos/UpdateUserAddressDto.ts
  backend/applications/users/usecases/UpdateUserAddressUsecase.ts
  backend/domain/repository/UpdateUserAddressRepository.ts
  backend/infrastructure/repository/UpdateUserAddressRepositoryImpl.ts
  hooks/main/useTransactionData.ts
  hooks/main/useTransactionDetail.ts
  hooks/main/useTransactionManagement.ts
  libs/api_front/userAddress.api.ts
  libs/stores/transactionData/transactionDataStore.ts
  libs/stores/userAddresses/userAddressStore.ts
  utils/main/transactionDetailUtils.ts
Labels: 📞 API, 🔙 Backend, 🔩 Feature, 🖥️ Frontend

#418 feat: textonly 각 슬라이드별로 읽음상태가 저장되도록 변경
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/ModalContent.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/CombinedContent.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/TextOnly.tsx
  app/(anon)/@detail/steps/[step-number]/[detail]/_components/contents/data/example-mixed-contents.json
  backend/infrastructure/repository/AddUserAddressRepositoryImpl.ts
Labels: 🔩 Feature

#421 [Refactor] 회원 탈퇴 버튼 연결 및 마이 페이지 제거
  app/(anon)/_components/common/header/PageTitle.tsx
  app/(anon)/_components/dashboard/HambugiDashboard.tsx
  app/(anon)/_components/dashboard/StepNavigation.styles.ts
  app/(anon)/_components/dashboard/StepNavigation.tsx
  app/(anon)/_components/dashboard/UserInfo.tsx
  app/(anon)/_components/dashboard/WithdrawButton.styles.ts
  app/(anon)/_components/dashboard/WithdrawButton.tsx
  app/(anon)/main/_components/DocumentCard.styles.ts
  app/(anon)/main/_components/DocumentCard.tsx
  app/(anon)/main/_components/MainPageComponent.tsx
  app/(anon)/mypage/_components/DocumentCard.styles.ts
  app/(anon)/mypage/_components/WithdrawButton.styles.ts
  app/(anon)/mypage/page.tsx
Labels: 🖥️ Frontend, 🛠️ Refactor
